/*** This file is auto generated by T4 template, please do not modify manually. ***/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using Abp.Domain.Entities;
using Abp.Domain.Entities.Auditing;

namespace MicroService.EntityFramework.Models
{
    /// <summary>
    /// 
    /// </summary>
    public partial class rc_cloudhisaccessauth : Entity<string>, IMustHaveTenant
    {
        public rc_cloudhisaccessauth()
        {
            // Set default value
            this.CHAAID = string.Empty;
            this.CreateTime = new DateTime(1900, 1, 1);
            this.ModifyTime = new DateTime(1900, 1, 1);
            this.UnitID = string.Empty;
            this.AuthCode = string.Empty;
            this.AccessToken = string.Empty;
            this.ExpireTime = new DateTime(1900, 1, 1);
            this.TenantCode = string.Empty;
            this.Remark = string.Empty;

        }

        /// <summary>
        /// 
        /// </summary>
        //public string Id { get; set; }
        /// <summary>
        /// 这是给数据库管理员用，业务不用
        /// </summary>
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 这是给数据库管理员用，业务不用
        /// </summary>
        public DateTime ModifyTime { get; set; }
        /// <summary>
        /// 医疗机构编码，机构的唯一标识，由云医院进行分配
        /// </summary>
        public string UnitID { get; set; }
        /// <summary>
        /// 认证编码，由云医院进行分配
        /// </summary>
        public string AuthCode { get; set; }
        /// <summary>
        /// accessToken 用于其他业务接口调用时进行鉴权；在业务请求消息接口中请求头（header）中携带该Token；该Token当日有效
        /// </summary>
        public string AccessToken { get; set; }
        /// <summary>
        /// AccessToken 过期时间
        /// </summary>
        public DateTime ExpireTime { get; set; }
        /// <summary>
        /// 机构ID
        /// </summary>
        public int TenantId { get; set; }
        /// <summary>
        /// 机构代码
        /// </summary>
        public string TenantCode { get; set; }
        /// <summary>
        /// 备注说明
        /// </summary>
        public string Remark { get; set; }

    }
}

